### PR TITLE
removed data-prop-location

### LINKED ISSUE #3: Do we need the data-prop-location?
### Feature summary

Hey Paul, again thank you for this package. I think it's a great idea and I'm very excited about it. I think it can be super useful. Where I work we use also headless CMSs and this tool could be great for frontend developers.

I'd like to start making some comments here and maybe some suggestions. But don't get overwhelmed! I know it's a very early version and we do this mostly on own our time.

First thing I'd like to ask you is about the `data-prop-location` attribute. Do we really need that? I mean, if we are inside a row, define by `data-row-name`, aren't we just creating all the properties in here for that row implicitely?

### Additional details

_No response_

### PR DESCRIPTION
**Pull request by skartknet**
Resolves #3 

I have removed the checking of the context when creating properties, assuming that all the properties belong to the wrapping context.

I just can't think of a situation where you want to create a page property while you're in the context of a row.

### CODE REVIEW

**Comment by prjseal** [comment]
Thanks @skartknet 
Have you tested that it still works after removing this?

**Comment by skartknet** [comment]
yes. No errors and everything seems to be in its place.
image

**Comment by prjseal** [comment]
That’s great. I was worried that some row or item properties would leak into the main page. 

Did you keep the context for row and Model so the partials still write out correctly?

**Comment by prjseal** [comment]
Hi Mario

Unfortunately, without the prop location context, all of the properties get added to the page. 

image

We need to change the parsing of properties first before we can merge this.

**Comment by skartknet** [comment]
Hey Paul. Ok, let me give it another try.

**Comment by prjseal** [comment]
Great. I asked the xpath question in the MVP channel and there is an answer. So you could try that in the method that gets properties from the HTML.

Here is the answer:
Off the top of my head, this should probably do it for you: //*[@data-prop-name][not(ancestor::*[@data-prop-name])]

**Comment by skartknet** [comment]
it's strange. I just ran a clean installation and ran QuickBlocks and the page looks good. I have removed a few of the sections from this example.

**Comment by skartknet** [comment]
I just saw your message on Slack. I must be getting something wrong here, but I don't think you would have a `data-prop-name` being descendant from another `data-prop-name`.

To find the props for a row we need to find those `data-prop-name` children of a `data-row-name` to find the row properties.

Then those `data-row-name` that are not children of a `data-row-name`  will belong to the page.

My tests have worked ok. Not sure why you got the properties in the page :/

**Comment by prjseal** [comment]
Yeah we would have descendants of data-prop-name, 

A block list property Main Content is a property of the page, and in that there are rows and in those they have properties and some of those properties could also be lists, and so it continues.

We can keep your initial PR, and I will fix the XPath separately then we should be able to merge this in.

**Comment by skartknet** [comment]
ah right. I get it now. :)

**Pull request merged**
