### PR TITLE
added data type mappers collections

### PR DESCRIPTION
**Pull request by skartknet**
I have added a collection to be able to add or modify the data type mappers. I have reconfigured the datatypes using this approach in a composer. 

Let me know if you need some explanation. I think this feature makes the package more flexible. Let me know your thoughts 😃 

I have also added some documentation so hopefully makes things clear.

### CODE REVIEW

**Review by prjseal — COMMENTED** [review]
I like this a lot. Just to clarify will this work by default without the user haveing to add a composer or edit the startup.cs. I want quick blocks to just work by default. 

I notice you put multiple classes in one file for the data type mappers. Does that need to be the case or can we split the classes into separate files? Or have I missed something?

**Comment by skartknet** [comment]
Yes, they will work by default. No need to configure anything unless you want to add a new mapper.

I put all the classes in the same file just because I'm lazy 😅. I can split them in different files.

**Comment by prjseal** [comment]
Great. If you could split up the classes that would be perfect. Thanks so much.

**Comment by prjseal** [comment]
I just tested it out and it all still works. Thank you.

**Pull request merged**
