### PR TITLE
Makes the view model name match the doctype in the html file

### PR DESCRIPTION
**Pull request by DeadMonkeyX**
Changes default view model name from HomePage to the name defined within the HTML file

### CODE REVIEW

**Comment by prjseal** [comment]
Hi mate. This is great thank you for submitting this so quickly. 

I think it might need to use the name though rather than the content type name and it needs to be Pascal Case like this. 


 ({newContentType.Name.ToCleanString(_shortStringHelper, CleanStringType.ConvertCase | CleanStringType.PascalCase)})

**Comment by DeadMonkeyX** [comment]
Good point but there is a problem:

If **data-content-type-name** in the html has the first 2 letters in uppercase like this: 

```data-content-type-name="CCode Garden Confrence"```

Then the models builder will create a model class that is named:

*CCodeGardenConfrence*

while this snippet below  will provide the name "CcodeGardenConfrence" (which is correct, but in terms of matching the model - wrong) 

```c#
                var templateClassName = newContentType.Name.ToCleanString(_shortStringHelper,
                    CleanStringType.ConvertCase | CleanStringType.PascalCase);
```

The `template.Alias` contains the correct naming :) 


Please reach out to me if I need to clarify more :)

**Comment by prjseal** [comment]
Yes you are correct and this causes other bugs. Maybe we should use the alias but capitalise the first letter of it?

**Comment by prjseal** [comment]
Thanks so much for this PR

**Pull request merged**
